# Generated by Django 4.1.2 on 2023-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_seasoncountry_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimumage', models.IntegerField()),
                ('maximumage', models.IntegerField()),
                ('factor', models.CharField(max_length=20)),
            ],
        ),
    ]
