# Generated by Django 4.1.2 on 2023-06-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_hobbyfactor_tb'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyname_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
