# Generated by Django 4.1.2 on 2023-06-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_register_tb_answer_register_tb_securityquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('filterstatus', models.CharField(default='pending', max_length=20)),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.register_tb')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.register_tb')),
            ],
        ),
    ]
