# Generated by Django 4.1.2 on 2023-06-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0006_agefactor_tb'),
        ('user', '0007_blacklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerhobbyfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyfactor_tb')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyname_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
